/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppFooter2: typeof import('./components/AppFooter2.vue')['default']
    copy: typeof import('./components/AppFooter copy.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./components/ui/toast.vue')['default']
    ToastLoading: typeof import('./components/ui/toast-loading.vue')['default']
    ToastNotifications: typeof import('./components/ui/toast-notifications.vue')['default']
  }
}
