/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/auth/verification': RouteRecordInfo<'/auth/verification', '/auth/verification', Record<never, never>, Record<never, never>>,
    '/client/dashboard': RouteRecordInfo<'/client/dashboard', '/client/dashboard', Record<never, never>, Record<never, never>>,
    '/client/map': RouteRecordInfo<'/client/map', '/client/map', Record<never, never>, Record<never, never>>,
    '/client/patients': RouteRecordInfo<'/client/patients', '/client/patients', Record<never, never>, Record<never, never>>,
    '/client/profile': RouteRecordInfo<'/client/profile', '/client/profile', Record<never, never>, Record<never, never>>,
    '/client/stats': RouteRecordInfo<'/client/stats', '/client/stats', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/about.vue': {
      routes: '/about'
      views: never
    }
    'src/pages/auth/login.vue': {
      routes: '/auth/login'
      views: never
    }
    'src/pages/auth/register.vue': {
      routes: '/auth/register'
      views: never
    }
    'src/pages/auth/verification.vue': {
      routes: '/auth/verification'
      views: never
    }
    'src/pages/client/dashboard.vue': {
      routes: '/client/dashboard'
      views: never
    }
    'src/pages/client/map.vue': {
      routes: '/client/map'
      views: never
    }
    'src/pages/client/patients.vue': {
      routes: '/client/patients'
      views: never
    }
    'src/pages/client/profile.vue': {
      routes: '/client/profile'
      views: never
    }
    'src/pages/client/stats.vue': {
      routes: '/client/stats'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
